### ISSUE TITLE
ValueChange does not work as expected with Picker

### ISSUE THREAD

**Issue by nise2** [testing-library/native-testing-library#123]
I am trying to use the [react-native-picker](https://github.com/react-native-community/react-native-picker) with [@testing-library/react-native](https://www.npmjs.com/package/@testing-library/react-native) latest version (v5.0.3).

The problem is that _valueChange_ event is not working as expected with the Picker component.

The following works with react-native-testing-library: `fireEvent(pickerComponent, valueChange, 'myValue');`
But with this library, it fails with : "Cannot read property 'charAt' of undefined". I would like to make it work with @testing-library/react-native.

I tried those implementation below, it ran without errors but did not trigger any updates.
* `fireEvent.change(pickerComponent, {target: {value: 'myValue'}});`
* `fireEvent.valueChange(pickerComponent, 'myValue');`

How I can make it work ? Did I miss something ?

**Comment by bitttttten** [comment]
I came here looking for the same solution!

[From the tests](https://github.com/testing-library/native-testing-library/blob/55c97168a995c128c4ff5f0e957318ebd0a2c52d/src/__tests__/misc.js#L20-L23) you can see that the valueChange is being triggered on the Picker.Item element, and not on the parent Picker component.

I thought I ran into this problem as my Picker has it's the default value to one that does not match any of the Picker.Items, so it renders the placeholder component. Still trying to work out how to fix that.

**Comment by callumbooth** [comment]
I've run into this issue myself with the [Date Time Picker](https://github.com/react-native-community/datetimepicker).

After looking into the issue I think this is related to #58 too.

From looking into it, the NativeTestEvent will only allow events from the event map defined [on this list](https://github.com/testing-library/native-testing-library/blob/master/src/lib/events.js#L18). But because the element that is being passed in has a type of "RNDateTimePicker" it doesn't match any keys in the event map then recursively bubbles up until in returns null.

For now you can mock the picker with:

```jest.mock('@react-native-community/datetimepicker', () => 'TextInput');```

I wonder if we didn't find the element in the event map the first time the `findEventTarget` function is called and the if statement still passes the other checks like the element passed has an eventHandler and its not disabled then we are safe to return the eventHandler?

**Comment by callumbooth** [comment]
Here is a mock for react-native-picker.

```js
jest.mock('@react-native-community/picker', () => {
  const React = require('React');
  return {
    Picker: class MockPicker extends React.Component {
      static Item = props => React.createElement('Item', props, props.children);

      render() {
        return React.createElement('Picker', this.props, this.props.children);
      }
    }
  };
});
```

**Comment by bitttttten** [comment]
I'm running into this with `react-native-picker-select` which uses the React Native Picker. I still haven't worked out a nice mock for it yet though as the component does a lot.
