### ISSUE TITLE
Rename testID to be consistent to react-testing-library

### ISSUE THREAD

**Issue by Pipo93** [testing-library/native-testing-library#28]
# Renaming of testID

In react-testing-library the `testID` property is named `data-testid`. For consistency reasons, in my opinion the property should be renamed to `data-testid`. Are there any reasons why it could not be renamed?

## Suggested Solution
Old:
`<Text testID="printed-username">{name}</Text>`

New:
`<Text data-testid="printed-username">{name}</Text>`

**Comment by lewie9021** [comment]
I believe the reason this library uses `testID` is because in the context of React Native, it's the standard way of applying test identifiers. Almost all native components support it along with a similar prop called `accessibilityLabel`.

- View: [testID](https://facebook.github.io/react-native/docs/view#testid), [accessibilityLabel](https://facebook.github.io/react-native/docs/view#accessibilitylabel).
- Text: [testID](https://facebook.github.io/react-native/docs/text#testid), [accessibilityLabel](https://facebook.github.io/react-native/docs/text#accessibilitylabel).

One of the benefits of using `testID` is that writing E2E tests with frameworks such as [Appium](https://github.com/appium/appium) and [Detox](https://github.com/wix/Detox) often require no additional changes to the codebase as these identifiers will already exist.

**Comment by Pipo93** [comment]
@lewie9021 okay, that makes sense... It's just bad in case you are developing cross-platform applications (Native / Web) where you do not want to write special tests for each platform.

**Comment by bcarroll22** [comment]
Hi @Pipo93, @lewie9021 is correct. In React Native, testID is an actual prop and data-testid isn’t. 

In any case, your test would be the same for both platforms. The thing that would be different would be your web/native components. `getByTestId(‘test’)` would select `testID=“test”` on native and `data-testid=“test”` in ReactDOM. 

We won’t be changing this because the prop wouldn’t mean anything to react native and because we don’t lose anything by not having it per my example above. Thanks for the question though, and good luck! ☺️

**Comment by bcarroll22** [comment]
@allcontributors please add @lewie9021 for answering a question
