### ISSUE TITLE
What about react-native-testing-library?

### ISSUE THREAD

**Issue by luizbaldi** [testing-library/native-testing-library#33]
Hi! 

I did some research and found [this library](https://github.com/callstack/react-native-testing-library) made by Callstack.

They really have a similar API and solves the same problem, right? There're plans to have a single `testing-library` for react native in the future?

And I'm sorry if this isn't the right place for this kind of question, I just wanna hear some opinions about this _scenario_ :)

**Comment by bcarroll22** [comment]
Hi Luiz, basically the reason both exist is that when this library was created the other one existed but didn’t closely adhere to the guiding principles of testing library. We had some discussion with the maintainers of that library about moving forward with one package under the @testing-library scope, but there wasn’t much interest. 

@kentcdodds might have some more to add, but I’m going to go ahead and close since that’s pretty much the answer 👍

**Comment by luizbaldi** [comment]
Thanks for your honesty @bcarroll22! I wish the best for `native-testing-library`.

Gonna start using in my projects :)

**Comment by lewie9021** [comment]
A [similar question was asked previously](https://github.com/testing-library/native-testing-library/issues/1) for anyone stumbling on this issue in the future :)
