### ISSUE TITLE
fireEvent.press() does not work for TouchableNativeFeedback

### ISSUE THREAD

**Issue by brendanmc6** [testing-library/native-testing-library#52]
- `react-native`
- `native-testing-library`: version 4.0.7
- `jest-preset`: @testing-library/react-native
- `react-native` version: 0.60.4
- `node` version: v10.16.0

I have two buttons. The only difference between them is which Touchable Feedback I use. The one with TouchableNativeFeedback is not testable, the one with TouchableHighlight is. I'm pretty sure this is an issue with native-testing-library. 

### Relevant code or config:
Here is the exact code I ran:
```jsx
export const TestableButton = ({ handlePress }) => (
  <TouchableHighlight onPress={handlePress}>
    <Text>FIND ME</Text>
  </TouchableHighlight>
);

export const UntestableButton = ({ handlePress }) => (
  <TouchableNativeFeedback onPress={handlePress}>
    <Text>FIND ME</Text>
  </TouchableNativeFeedback>
);
```

My test looks like this. It passes for TestableButton, fails for UntestableButton
```js
test('calls handlePress', async () => {
  const mockHandlePress = jest.fn();
  const { getByText } = render(
    <TestableButton handlePress={mockHandlePress} />
  );
  const button = getByText('FIND ME');
  fireEvent.press(button);
  expect(onPress).toHaveBeenCalled();
});
```

This is currently preventing me from adopting this library because we use TouchableNativeFeedback everywhere, and it makes testing my components impossible if I can't simulate presses. Happy to open a PR if you can point me in the right direction!

Thanks!

**Comment by bcarroll22** [comment]
Thanks for raising this! This is a very interesting problem after looking into it.

So basically, Jest's default "platform" that it runs tests in is iOS. For the iOS platform, the display name of the component rendered when you render a `TouchableNativeFeedback` is `DummyTouchableNativeFeedback`. Because of this, our logic to find and filter components doesn't find it because we're looking for a component named `TouchableNativeFeedback`.

I'm not really sure what the easiest way to address this is unfortunately. Big picture, the React Native community really needs a much better set of mocks for testing, because specific issues like this keep coming up, and I unfortunately don't have time to build or maintain the mocks ☹️ 

Shorter term, you could potentially try mocking the platform to be android instead of iOS for your tests, but I can't guarantee that wouldn't introduce other issues. Until we have a better mock infrastructure, I don't think we'll be able to fully address issues like this (think JSDOM but for RN).

**Comment by bcarroll22** [comment]
For historical context for anyone reading, we've got a rock-and-a-hard-place situation with our approach and philosophy.

To adhere to the guiding principles of Testing Library, and only write tests the way users use the app, we have to filter out components in our queries so that they're only the "native" components a user can see/use. This means you can't query for your own implementation components, and you can really only query for the ones that are built into React Native.

That said, it introduces some weird scenarios like this where the internals of React Native create some hardships when we're trying to filter query results. I don't believe the right thing to do is loosen on our adherence to the guiding principles, but I also understand the problems it creates for some of our users.

My plan is to keep asking the community that uses this library to join together to create a much more sophisticated mock platform/jest preset intended to be used in conjunction with this library, and apologize that I can't help with it more 😞

**Comment by brendanmc6** [comment]
Thanks for the quick response. In the end I just installed callstack's `react-native-testing-library` and swapped the import, now my tests pass.

I have no idea what the differences are between this repo and `react-native-testing-library`. Have you looked to see what their solution is to this problem? This might not be the right place to discuss this, but I'm wondering why there two near-identical repos, with the same API and even matching docs pages...

**Comment by TAGraves** [comment]
In my opinion, the behavior here is correct since those touchable don’t in fact work on iOS. Maybe we should provide better support for setting the platform?

**Comment by bcarroll22** [comment]
@TAGraves 🤔 that's a good point, we should probably do that.

@brendanmc6 👍 happy you came up with a solution!

**Comment by bcarroll22** [comment]
I'm going to go ahead and close since this isn't an active issue anymore, and we can do some investigation on making it easier to set the platform for tests.

**Comment by devproivansurzhenko** [comment]
@bcarroll22 @brendanmc6 Is the following issue could be a side-effect of this topic? https://github.com/facebook/react-native/issues/27721
