### ISSUE TITLE
Custom Events not triggered

### ISSUE THREAD

**Issue by northbank** [testing-library/native-testing-library#58]
- `react-native` or `expo`: `react-native`
- `native-testing-library` version: `4.0.9`
- `jest-preset`: `@testing-library/react-native`
- `react-native` version: `0.59`
- `node` version: `12.6.0`

### What you did:

```js
fireEvent(getByTestId('SegmentedControlIOS'), new NativeTestEvent('change',  { nativeEvent: { selectedSegmentIndex: 1, value: 'some value' }}))
```

### What happened:

event does not get triggered

### Reproduction:

https://github.com/northbank/ntl-sample

### Problem description:

Event listeners on components _not_ in the `eventMap` in `src/lib/events.js` do not get triggered if the event could have belonged to one of the arrays in the `eventMap`

### Suggested solution:

```
+function shouldValidate(element) {
+  return eventMap[element.type] || eventMap[element.type.displayName];
+}
+
 function isValidTarget(element, event) {
-  return event.validTargets.length ? validateElementType(event.validTargets, element) : true;
+  return shouldValidate(element) ? validateElementType(event.validTargets, element) : true;
 }
```

### Can you help us fix this issue by submitting a pull request?

yes

**Comment by bcarroll22** [comment]
Ah this is a tough one. The custom event functionality is left over from before we had a jest preset, and now that we have the jest preset I'm not sure that there's a great/easy way to run custom events on custom components.

The only way I can think of currently would be to call `configureNTL` yourself from your own setup file that includes your components in the list of core components. I may look into how to make that more extensible at some point, but given that the preset stuff has to run during the setup phase, it's kinda hard/maybe impossible to make it extensible.

I'm open to suggestions or ideas for how to improve it, but I don't have any others off the top of my head. Platform-specific components like `SegmentedControlIOS` and other components that were intended to be removed from react-native core aren't included in our jest preset because once they're extracted from react-native, I didn't want to have support for a small set of "third-party" components.

**Comment by thymikee** [comment]
FYI, this repository is no longer responsible for this package. See the [migration guide to v7.0](https://callstack.github.io/react-native-testing-library/docs/migration-v7/) and check if the issue is fixed there.
