### ISSUE TITLE
est suite failed to run => babel-plugin-jest-hoist: The second argument of `jest.mock` must be an inline function.

### ISSUE THREAD

**Issue by mauriciord** [testing-library/native-testing-library#68]
### Environment
```
  Expo CLI 3.4.0 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^4.0.7 => 4.0.7
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.4.0
```

app's target: **Standalone**

```js
// jestconfig.js

const expoPreset = require('jest-expo/jest-preset');
const jestPreset = require('@testing-library/react-native/jest-preset');

module.exports = Object.assign({}, expoPreset, jestPreset, {
  setupFiles: [...expoPreset.setupFiles, ...jestPreset.setupFiles, './jestSetup.js'],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)',
  ],
});
```

```js
// jestSetup.js

import mocks from 'react-native-jest-mocks';

mocks.initAll();

// eslint-disable-next-line no-underscore-dangle
global.__DEV__ = false;

```

### Steps to Reproduce

I'm trying to run my tests using `yarn test`

```json
"test": "jest -i --colors --config jestconfig.js",
```

### Expected Behavior

My test run normally

### Actual Behavior

I get this error:

<img width="632" alt="Screen Shot 2019-10-24 at 14 39 48" src="https://user-images.githubusercontent.com/1128701/67510876-2ccc5400-f66c-11e9-9d9a-701dffe7e454.png">

**Comment by bcarroll22** [comment]
Hmm I'm not sure what would be causing this, but it doesn't look like anything in the error stack traces points to this library. Is there something that leads you to believe this is a bug with this library and not simply an issue with your project's specific setup?

I don't see anything that stands out, but it does seem like this is something related to some of the other libraries you're using like possibly the `react-native-jest-mocks` library. I'm going to go ahead and close because I'm confident this isn't related to this library (since we don't show up in the stack trace) but it's rather caused by something else. Sorry I can't point you in the right direction. Good luck!

**Comment by mauriciord** [comment]
Thank you @bcarroll22 
The issue is on the lib `react-native-jest-mocks`.

https://github.com/Xabadu/react-native-jest-mocks/issues/18

**Comment by adamya2797** [comment]
@mauriciord How did you solve this?
