### ISSUE TITLE
validRole and validTraits restricted

### ISSUE THREAD

**Issue by ajsmth** [testing-library/native-testing-library#72]
I'm wondering why there are only a few options that can be selected via `queryByRole` as defined in role.js: 

```js

const validRoles = [
  'adjustable',
  'button',
  'header',
  'image',
  'imagebutton',
  'keyboardKey',
  'link',
  'none',
  'search',
  'summary',
  'text',
];

const validTraits = [
  'adjustable',
  'allowsDirectInteraction',
  'button',
  'disabled',
  'frequentUpdates',
  'header',
  'image',
  'key',
  'link',
  'none',
  'pageTurn',
  'plays',
  'search',
  'selected',
  'startsMedia',
  'summary',
  'text',
];
```

Looks like there's a whole bunch of other roles that are defined by React Native: https://facebook.github.io/react-native/docs/accessibility#accessibilityrole-ios-android 

I'm wondering if this was a design decision, and if so how we could override / configure this

**Comment by bcarroll22** [comment]
Hey thanks for pointing this one out too! In one of the more recent releases of RN, probably 60,  they added a lot more accessibility options. This feature was implemented before the extended list of roles was available. It wasn't an intentional omission, just hasn't been updated yet. We can add all of the currently available roles so that they're available for queries as well.

**Comment by ajsmth** [comment]
awesome -- i can add these if you'd like!
