### ISSUE TITLE
provided preset does not cover native-module event-emitter 

### ISSUE THREAD

**Issue by cdaringe** [testing-library/native-testing-library#85]
- `react-native` or `expo`: └─ react-native@0.60.5
- `native-testing-library` version: └─ @testing-library/react-native@5.0.1
- `jest-preset`: this library's, as recommended https://www.native-testing-library.com/docs/install#jest-preset
- `react-native` version: └─ react-native@0.60.5
- `node` version: v11.8.0

### Relevant code or config:

```js
// jest.config.js

const testingLibraryJestPreset = require('@testing-library/react-native/jest-preset');

module.exports = {
  preset: '@testing-library/react-native',
  setupFiles: [...testingLibraryJestPreset.setupFiles],
  ...
}
```

### What you did:

`npx jest`

### What happened:

crash on falsy presence of `NativeEventEmitter`

```
 ● Test suite failed to run

    Invariant Violation: Native module cannot be null.

      1 | // @flow
      2 | import React from 'react';
    > 3 | import { render } from '@testing-library/react-native';
        | ^
      4 | import TestRenderer from 'react-test-renderer';
      5 |

      at invariant (node_modules/invariant/invariant.js:40:15)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:36:7)
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/Keyboard/Keyboard.js:19:30)
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/ScrollResponder.js:15:18)
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/ScrollView/ScrollView.js:17:25)
      at mockComponent (node_modules/@testing-library/react-native/dist/preset/mock-component.js:26:28)
      at Object.user:/Users/cdaringe/src/myapp/node_modules/react-native/Libraries/Components/ScrollView/ScrollView.js: (node_modules/@testing-library/react-native/dist/preset/mock-modules.js:22:47)
      at Object.<anonymous> (node_modules/react-native/Libraries/Lists/VirtualizedList.js:18:20)
      at Object.<anonymous> (node_modules/react-native/Libraries/Lists/FlatList.js:16:25)
      at Object.<anonymous> (node_modules/react-native/Libraries/YellowBox/UI/YellowBoxList.js:15:18)
      at Object.<anonymous> (node_modules/react-native/Libraries/YellowBox/YellowBox.js:50:25)
      at Object.<anonymous> (node_modules/react-native/Libraries/ReactNative/AppContainer.js:132:23)
      at Object.<anonymous> (node_modules/@testing-library/react-native/dist/index.js:37:44)
      at Object.<anonymous> (src/__tests__/app.test.js:3:1)
```

### Reproduction:

- i'm willing to make one of these, but i'd like to have a discussion first if feasible

### Problem description:

- tests wont run due to invariant violation due to missing mocks? for native modules

### Suggested solution:

this issue is generally discussed verbatim here:

https://github.com/facebook/jest/issues/2208

it's a bit of a messy thread, but more or less lands on that the presets should mock this out.  in our case, it didn't seem to do so 🤔 

### Can you help us fix this issue by submitting a pull request?

💯 .  however, i could use some coaching.  whilst doing s/w and react for a long while, i'm brand new to RN :)

**Comment by bcarroll22** [comment]
Hey thanks for raising the issue! 

We've discussed this quite a few times in other issues in the past, I don't believe a complete/thorough set of React Native mocks should live inside of this library. It's intended to be light-weight and mostly maintain the same footprint/scope as the rest of *-testing-library. Honestly, I hate that we even have a jest preset 😬

To give you a bit of background on the preset, it doesn't really do much. We pretty much lightly extend the default RN preset, and we only do it so that we can handle `debug()` and create snapshots in a way that follows the [guiding principles](https://testing-library.com/docs/guiding-principles). We created it so that we could adhere to the guiding principles... but I wish we didn't have to. 😅

My belief on this hasn't changed, there should be another package created and maintained separately that's basically like a JSDOM for React Native (that package would include a full set of component mocks and native module mocks).

For your use case, it's probably best to create your own mocks for native modules using `setupFilesAfterEnv` and extending the provided native modules mocks. Admittedly though, some native module mocking is likely going to be out of scope for any current library testing RN ☹️ its one of the biggest opportunities in the ecosystem.

Sorry I can't be more help than that, it's kinda an unfortunate limitation of the current state of things in RN testing, and I just don't want the scope of this project to start getting that big.

**Comment by cdaringe** [comment]
thx @bcarroll22.  i'm starting to put this all together :) . ya, your take makes sense.  a jsdom-y RN thing _really does feel_ like the ideal solution.  for better or worse, i hacked around this with:

**Comment by bcarroll22** [comment]
That’s very similar to what we do in our projects as well, I think it’s the best approach for now. 

Good luck, and welcome to the react native family! 😀

**Comment by justDanielMata** [comment]
is there anywhere i can see a comer coimplete example of this? i have tried to mock the event emitter everywhere at this point and i still can't get the error to go away. 

`Native Module cannot be null` when trying to test a component that includes a `KeyboardAvoidingView`

Also, while i agree with you that a full set of mocks is probably outside the scope of the library, maybe adding a small section to the docs talking about mocking native modules could be good, as its such a common thing that will happen

**Comment by cdaringe** [comment]
In rn 59, I would mock `NativeEventEmitter`, but for some undiagnosed reason in 60 I had to mock the relative path to the JS file
