### ISSUE TITLE
implement closest

### ISSUE THREAD

**Issue by sibelius** [testing-library/native-testing-library#89]
**Describe the feature you'd like:**

I'd like to have a similar `closest` function/helper of react-testing-library to find elements closest to another

Use case: find a Button/TouchableOpacity from the text inside of it

debug output

```jsx
<TouchableOpacity
                            activeOpacity={0.2}
                          >
                            <Text
                              color="#e8ecf0"
                            >
                              Save
                            </Text>
```

`const button = getByTest('Save').closest('TouchableOpacity')`

**Suggested implementation:**

try to follow the react/dom implementation

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by bcarroll22** [comment]
Hello again! So this isn’t actually a feature in testing library, this is a feature of JSDOM/the browser DOM. 

I suppose we could look into adding it, but this isn’t a feature of the core testing library API, so I don’t know that we’d want to break from it. My hesitancy for implementing features like this has always been that NTL will end up scope creeping much larger than the rest of the family and then it would be hard to maintain API parity with them if there’s a big change because of the increased scope.
